.TH SEGYIO-CATB 1
.SH NAME
segyio-catb \- Concatenate SEG-Y binary header and print on seismic unix format
.SH SYNPOSIS
.B segyio-catb
[\fIOPTION\fR]...
[\fIFILE\fR]...
.SH DESCRIPTION
.B segyio-catb
Concatenate the SEG-Y binary header in FILEs.

.SH OPTIONS
.TP
.BR \-\-version
output version information and exit

.TP
.BR \-\-help
display this help and exit

.SH COPYRIGHT
Copyright © Statoil ASA. License LPLv3+: GNU LGPL version 3 or later <http://gnu.org/licenses/lgpl.html>.

.PP
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.   

.SH SEE ALSO
segyio-cath(1), segyio-catb(1)
